### ISSUE TITLE
Request for circuit diagram

### ISSUE THREAD

**Issue by jrssae** [martinux/proton_pack_arduino#1]
This seemed like the best place to request. I'm building the same thing you did and would really appreciate any help you could give on the circuit layout. Any chance you could post the circuit diagrams?

**Comment by martinux** [comment]
![breadboard_fritzing](https://cloud.githubusercontent.com/assets/4701895/10117449/f426a190-644e-11e5-8ffe-9db9a4d45dc3.png)
![gun_board](https://cloud.githubusercontent.com/assets/4701895/10117489/9ea8a37e-6450-11e5-86ba-ecc6284b9827.jpg)

The circuits are standard 595 shift registers. Whilst I don't have schematics to hand I suggest you have a look at the diagram attached and the arduino shift-register tutorials. They're pretty straightforward. I built mine on stripboard.

**Comment by jrssae** [comment]
Thanks, this is really helpful!

**Comment by betchasketch** [comment]
I know this is an older thread but do you happen to have photos or a finished diagram with the soundboard and cyclotron lights attached to the arduino?
